language: java

matrix:
   include:
      # code coverage with coveralls
      - os: linux
        dist: xenial
        jdk: openjdk8
        env: ADDITIONAL_MAVEN_ARGS="-Pjacoco coveralls:report"
      # only on PR
      - os: linux
        dist: xenial
        jdk: openjdk9
        if: type IN (pull_request)
      # JDK11  
      - os: linux
        dist: xenial
        jdk: openjdk11
        
services:
      - docker

install: true

cache:
   directories:
      - $HOME/.m2

script:
   - mvn -f com.unifi.attsw.exam.museum-app/pom.xml clean verify $ADDITIONAL_MAVEN_ARGS
