language: java

matrix:
   include:
      - jdk: openjdk8
      - jdk: openjdk9
        if: type IN (pull_request)

services:
      - docker

install: true

cache:
   directories:
      - $HOME/.m2

script:
   - mvn -f com.unifi.attws.exam.museum-app/pom.xml clean verify -Pjacoco
