# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: build
on: ["push"]

jobs:
  build_push:
    name: PIT, Coveralls, Java 11
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'    

    - name: Setup Docker
      uses: docker-practice/actions-setup-docker@master
      with:
        docker_version: 19.03
        docker_channel: stable
          # this value please see https://github.com/AkihiroSuda/moby-snapshot/releases
        docker_nightly_version: snapshot-20201109
    - name: Maven Build
      run: xvfb-run --auto-servernum --server-args "-screen 0 1024x768x24" ./mvnw -f museum-manager/museum-manager-aggregator/pom.xml clean verify $ADDITIONAL_MAVEN_ARGS -DrepoToken=$COVERALLS_REPO_TOKEN 
      env: 
        ADDITIONAL_MAVEN_ARGS: -Pjacoco,pit,coveralls,build-app
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

                
      
