# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: build
on: ["push", "pull_request"]

jobs:
  build_push:
    name: PIT, Coveralls, Java 8
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master
        with:
          docker_version: 19.03
          docker_channel: stable
          # this value please see https://github.com/AkihiroSuda/moby-snapshot/releases
          docker_nightly_version: snapshot-20201109
      - name: Maven Build
        run: xvfb-run --auto-servernum --server-args "-screen 0 1024x768x24" mvn -f com.unifi.attsw.exam.museum-app/pom.xml clean verify -DrepoToken=$COVERALLS_REPO_TOKEN $ADDITIONAL_MAVEN_ARGS
        env: 
          ADDITIONAL_MAVEN_ARGS: org.pitest:pitest-maven:mutationCoverage -Pjacoco coveralls:report
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
  build_PR:
    name: Pull Request
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.9
        uses: actions/setup-java@v1
        with:
          java-version: 1.9
      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master
        with:
          docker_version: 19.03
          docker_channel: stable
          # this value please see https://github.com/AkihiroSuda/moby-snapshot/releases
          docker_nightly_version: snapshot-20201109
      - name: Maven Build on PR
        run: xvfb-run --auto-servernum --server-args "-screen 0 1024x768x24" mvn -f com.unifi.attsw.exam.museum-app/pom.xml clean verify
        


                
      
