# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8 and xvfb
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: sudo apt-get install xvfb
      - name: Setup docker
        uses: docker-practice/actions-setup-docker@master
        with:
          docker_version: 19.03
          docker_channel: stable
          # this value please see https://github.com/AkihiroSuda/moby-snapshot/releases
          docker_nightly_version: snapshot-20201109
        env: 
          ADDITIONAL_MAVEN_ARGS: org.pitest:pitest-maven:mutationCoverage -Pjacoco coveralls:report
      - name: Build with Maven
        run: xvfb-run mvn -f com.unifi.attsw.exam.museum-app/pom.xml clean verify $ADDITIONAL_MAVEN_ARGS
      
